"""
Generate Quartus .mif memory-initialisation files for the FPGA self-test.

Produces three ROMs that get compiled into the bitstream:

    weights   K*M bytes   already in SHIFT ORDER, so the harness just
                          streams them out; no reordering in hardware
    acts      N*K bytes   activation vectors, one K-vector per row
    expected  N*M words   golden results from tb/ref_model.py

Each is written twice: .mif for Quartus, .txt for $readmemb in simulation.

Vectors come from the real trained checkpoint when it is present, and from a
seeded RNG otherwise, so the flow works on any machine.

    python fpga/gen_test_vectors.py
    python fpga/gen_test_vectors.py --vectors 32 --seed 7
"""

import argparse
import random
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent          # hardware/
REPO_ROOT = ROOT.parent                                # repo root
sys.path.insert(0, str(ROOT / "rtl" / "tb"))
from ref_model import matvec, random_activations, random_weights, weight_shift_order  # noqa: E402


def parse_args():
    p = argparse.ArgumentParser(description="Build .mif vectors for the FPGA self-test")
    p.add_argument("--k", type=int, default=16, help="array rows (reduction depth)")
    p.add_argument("--m", type=int, default=16, help="array columns (output channels)")
    p.add_argument("--vectors", type=int, default=64, help="activation vectors to stream")
    p.add_argument("--acc-w", type=int, default=32)
    p.add_argument("--seed", type=int, default=0xC0FFEE)
    p.add_argument("--layer", default="conv2", choices=list(CONV_INDEX),
                   help="which conv layer's weights to tile onto the array")
    p.add_argument("--out", default=str(Path(__file__).resolve().parent))
    return p.parse_args()


# Conv layer -> index in model.py's nn.Sequential. features[3] is Conv2d(32,64),
# verified against src/model.py rather than assumed.
CONV_INDEX = {"conv1": 0, "conv2": 3, "conv3": 7, "conv4": 11}


def find_weight_source(root, layer):
    """Return (flat_weights_2d, description) or None.

    Prefers a .npz export (portable, no torch needed) over the .pt checkpoint.

    Loud about failure on purpose. The earlier version swallowed every
    exception and fell back to random, so a PyTorch version mismatch looked
    identical to having no checkpoint at all -- and the only visible symptom
    was one word of console output.
    """
    import numpy as np

    npz = root / "software" / "results" / "checkpoints" / "conv_weights.npz"
    if npz.exists():
        d = np.load(npz)
        if layer in d:
            w = d[layer]
            return w.reshape(w.shape[0], -1), f"{npz.name}:{layer}"
        print(f"note      : {npz.name} has no '{layer}' "
              f"(has {', '.join(d.files)})")

    ckpt = root / "software" / "results" / "checkpoints" / "baseline_best.pt"
    if not ckpt.exists():
        return None

    try:
        import torch
    except ImportError:
        print(f"note      : {ckpt.name} found but PyTorch is not installed; "
              f"ask for a conv_weights.npz export instead")
        return None

    state = None
    for kw in ({"weights_only": True}, {"weights_only": False}):
        try:
            state = torch.load(ckpt, map_location="cpu", **kw)
            break
        except Exception as exc:
            last = exc
    if state is None:
        print(f"note      : {ckpt.name} would not load ({type(last).__name__}: "
              f"{str(last)[:80]}); ask for a conv_weights.npz export")
        return None

    sd = state.get("model_state_dict", state) if isinstance(state, dict) else state
    key = f"features.{CONV_INDEX[layer]}.weight"
    if key not in sd:
        cands = [k for k in sd if k.endswith(".weight") and sd[k].dim() == 4]
        print(f"note      : {ckpt.name} has no '{key}'; 4-D weights present: "
              f"{', '.join(cands) or 'none'}")
        return None

    w = sd[key].detach().cpu().numpy()
    return w.reshape(w.shape[0], -1), f"{ckpt.name}:{key}"


def write_mem(path, width, depth, values):
    """Plain binary, one word per line -- what $readmemb expects.

    Quartus cannot read this and Icarus cannot read a .mif, so both are
    written from the same values and the two flows stay in lockstep.
    """
    mask = (1 << width) - 1
    with open(path, "w", encoding="utf-8") as f:
        for v in values:
            f.write(f"{(int(v) & mask):0{width}b}" + chr(10))
        for _ in range(depth - len(values)):
            f.write("0" * width + chr(10))
    return path


def write_mif(path, width, depth, values):
    """Quartus memory-initialisation file, binary radix, one word per line."""
    mask = (1 << width) - 1
    with open(path, "w", encoding="utf-8") as f:
        f.write(f"-- generated by fpga/gen_test_vectors.py\n")
        f.write(f"DEPTH = {depth};\nWIDTH = {width};\n")
        f.write("ADDRESS_RADIX = DEC;\nDATA_RADIX = BIN;\n\nCONTENT BEGIN\n")
        for addr, v in enumerate(values):
            f.write(f"    {addr} : {(int(v) & mask):0{width}b};\n")
        if len(values) < depth:                 # pad, Quartus requires full range
            f.write(f"    [{len(values)}..{depth-1}] : {0:0{width}b};\n")
        f.write("END;\n")
    return path


def main():
    a = parse_args()
    out = Path(a.out)
    rng = random.Random(a.seed)

    weights = None
    src = find_weight_source(REPO_ROOT, a.layer)
    if src is not None:
        import numpy as np
        flat, note = src
        scale = float(np.abs(flat).max()) / 127.0
        q = np.clip(np.round(flat / scale), -128, 127).astype(int)
        if q.shape[0] < a.m or q.shape[1] < a.k:
            print(f"weights   : {note} is {q.shape}, too small for "
                  f"{a.m}x{a.k}; using random")
        else:
            weights = [[int(q[m][k]) for k in range(a.k)] for m in range(a.m)]
            print(f"weights   : REAL {a.layer} tile from {note}, "
                  f"scale={scale:.6g}")
            print(f"            full layer is {q.shape[0]}x{q.shape[1]}, "
                  f"taking the top-left {a.m}x{a.k}")
    if weights is None:
        weights = random_weights(a.m, a.k, rng)
        print(f"weights   : random, seed 0x{a.seed:X}")
        print( "            (drop software/results/checkpoints/baseline_best.pt")
        print( "             to use the trained model instead)")

    acts = random_activations(a.k, a.vectors, rng)
    expected = [matvec(weights, v) for v in acts]

    # Weights leave in SHIFT ORDER: cycle i carries W[m][K-1-i] for every m,
    # packed as one M*8-bit word so the harness drives w_top directly.
    shift_words = []
    for col_bytes in weight_shift_order(weights, a.k):
        word = 0
        for m, b in enumerate(col_bytes):
            word |= (int(b) & 0xFF) << (m * 8)
        shift_words.append(word)

    act_words = []
    for vec in acts:
        word = 0
        for k, v in enumerate(vec):
            word |= (int(v) & 0xFF) << (k * 8)
        act_words.append(word)

    exp_words = []
    for res in expected:
        word = 0
        for m, v in enumerate(res):
            word |= (int(v) & ((1 << a.acc_w) - 1)) << (m * a.acc_w)
        exp_words.append(word)

    for stem, width, depth, vals in (
        ("weights",  a.m * 8,       a.k,       shift_words),
        ("acts",     a.k * 8,       a.vectors, act_words),
        ("expected", a.m * a.acc_w, a.vectors, exp_words),
    ):
        write_mif(out / f"{stem}.mif", width, depth, vals)   # Quartus
        write_mem(out / f"{stem}.txt", width, depth, vals)   # $readmemb

    print(f"array     : K={a.k} M={a.m} ACC_W={a.acc_w}, {a.vectors} vectors")
    print(f"weights .mif/.txt  {a.k:5d} x {a.m*8:5d} bit")
    print(f"acts    .mif/.txt  {a.vectors:5d} x {a.k*8:5d} bit")
    print(f"expected.mif/.txt  {a.vectors:5d} x {a.m*a.acc_w:5d} bit")
    total = a.k*a.m*8 + a.vectors*a.k*8 + a.vectors*a.m*a.acc_w
    print(f"total ROM    {total:,} bits = {total/8/1024:.1f} KiB "
          f"({total/(6480*1024):.2%} of the EP4CGX150's M9K)")
    print(f"\nwritten to {out}")


if __name__ == "__main__":
    main()
